# APPLICATION
spring.application.name=SiliconOven

# SERVER
server.port=8081
server.address=0.0.0.0

# PostgreSQL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5433/silicon
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Entity scanning
spring.jpa.properties.hibernate.entity_search_strategy=class

# JWT
jwt.secret=UusuriKeyForJWTTokenGenerationAndValidation1234567890
jwt.expiration=60000000
